module_orders/urls.py
from django.urls import path
from .views import orders_cart_view, ajax_delete_from_cart, ajax_delete_from_sidebar, ajax_change_amount, checkout_view, ajax_add_to_cart
from .payment_verify_views import verify_payment_view

urlpatterns = [
    path('cart', orders_cart_view, name="urls_cart"),

    # ajax_delete from cart page
    path('cart/ajax/c-delete/', ajax_delete_from_cart, name="urls_ajax_delete_cart_page_item"),

    # ajax_delete from sidebar cart
    path('cart/ajax/s-delete/', ajax_delete_from_sidebar, name="urls_ajax_delete_side_cart_item"),

    path('cart/json/amount/', ajax_change_amount, name="urls_ajax_change_amount"),

    path('checkout/', checkout_view, name="urls_checkout"),
    path('checkout/<repay_cart_id>', checkout_view, name="urls_checkout_repay"),

    path('verify/', verify_payment_view, name="urls_verify_payment"),
    path('verify/<cart_id>', verify_payment_view, name="urls_verify_payment_callback"),


    path('ajax/add_to_cart/', ajax_add_to_cart, name="urls_ajax_add_to_cart"),
]


app_name = "module_orders"

module_products/urls.py
from django.urls import path
from .views import ProductsCategoriesView, product_detail_view, Products_SearchAndTag_View, ajax_wishlist

urlpatterns = [
    path('search', Products_SearchAndTag_View.as_view(), name="urls_products_search_tag"),
    path('<main_category>', Products_SearchAndTag_View.as_view(), name="urls_products_list"),
    path('<main_category>/<sub_category>', Products_SearchAndTag_View.as_view(), name="urls_product_list_sub_category"),

    # path('<main_category>', Products_Categories_View.as_view(), name="urls_products_list"),
    # path('<main_category>/<sub_category>', Products_Categories_View.as_view(), name="urls_product_list_sub_category"),

    path('detail/<p_id>/<slug>', product_detail_view, name="urls_product_detail"),

    path('ajax/wishlist_add_remove/', ajax_wishlist, name="urls_ajax_wishlist"),

    path('', ProductsCategoriesView.as_view(), name="urls_products_list_filter"),

]


app_name = "module_products"

module_users/urls.py
from django.urls import path
from .views import log_out_view
from .views import login_view, ajax_email_phone, ajax_password, ajax_otp, ajax_otp_reset, ajax_register

urlpatterns = [
    path('login/', login_view, name="urls_Login_Page"),
    path('login/email-phone/', ajax_email_phone, name="urls_ajax_email_phone"),

    path('login/ajax_password/', ajax_password, name="urls_ajax_password"),
    path('login/ajax_otp/', ajax_otp, name="urls_ajax_otp"),
    path('login/ajax_otp_reset/', ajax_otp_reset, name="urls_ajax_otp_reset"),  # Do not change (used in layout)
    path('login/ajax_register/', ajax_register, name="urls_ajax_register"),

    path('logout', log_out_view, name="urls_Logout"),
]


app_name = "module_users"

termos_eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_page, about_us_view, terms_view, sys_view, admin_links

# to use assets
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home_page, name="urls_Home_Page"),
    path('about-us', about_us_view, name="urls_about_us"),
    path('terms-conditions', terms_view, name="urls_terms"),
    # path('', AjaxHandlerView.as_view(), name="urls_Home_Page"),
    path('user/', include("module_users.urls", namespace="module_users")),
    path('products/', include("module_products.urls", namespace="module_products")),
    path('orders/', include("module_orders.urls", namespace="module_orders")),
    path('profile/', include("module_profile.urls", namespace="module_profile")),
    path('product_comments/', include("module_product_comments.urls", namespace="product_comments")),
    path('contact-us/', include("module_contact.urls", namespace="module_contact-us")),


    path('sys', sys_view, name="urls_sys"),


    path('termos_admin_panel/', admin.site.urls),
    path('edit_product/<p_id>', admin_links, name="admin_product_editor"),
]


if settings.DEBUG:
    # add root static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

module_products/views.py
from django.template.loader import render_to_string
from django.http import Http404, JsonResponse
from django.shortcuts import render
from module_SiteSettings.models import site_settings
from module_products.models import Product
from module_categories.models import ProductCategories, Product_SubCategories
from django.views.generic import ListView
from module_orders.forms import add_order_form
from module_product_comments.forms import ProductCommentsForm
from module_product_comments.models import Product_Comments_Model
from django.conf import settings
from django.db.models import Q
from django.urls import reverse
from termos_eshop.Utilities import giveme_cart, give_me_the_product_by_id
from termos_eshop.Utilities import is_ajax, bad_request_ajax_error


# ---------------------------------------------------------------- Categories View


# This class have to check again
class ProductsCategoriesView(ListView):
    template_name = "ProductsListLayout.html"
    paginate_by = 10

    def get_queryset(self):
        start_price, end_price, category_slug, sub_category_slug = 0, 0, None, None
        price_filter = False
        if is_ajax(self.request):
            self.template_name = "Component/AjaxProductsList.html"

            rolling: list = self.request.headers['Referer'].split('/products/')
            cat_names: list = rolling[1].split('/')
            if len(cat_names) == 1:
                category_slug = cat_names[0]
            elif len(cat_names) == 2:
                category_slug = cat_names[0]
                sub_category_slug = cat_names[1]
            else:
                raise Http404("درخواست نامعتبر")
            # Filter Process
            filter_price = self.request.GET.get('price_limit').split(' - ')
            start_price = int(filter_price[0].replace(',', ''))
            end_price = int(filter_price[1].replace(',', ''))
            price_filter = True

        else:
            try:
                category_slug = self.kwargs["main_category"]
            except KeyError:
                category_slug = None
            try:
                sub_category_slug = self.kwargs["sub_category"]
            except KeyError:
                sub_category_slug = None

        # --
        main_category = ProductCategories.objects.filter(slug=category_slug)

        header_cart, total_cart_price = giveme_cart(self.request)
        if main_category.count() > 0:
            main_category = main_category.first()
        else:
            raise Http404("صفحه مورد نظر یافت نشد")

        all_categories: ProductCategories = ProductCategories.objects.all()
        s_settings = site_settings.objects.first()
        self.extra_context = {
            'site_settings': s_settings,
            'main_category': main_category,
            'category_bar': all_categories,
            'found_product_count': Product.objects.get_by_categories(category_title=main_category.title).count(),
            'header_cart': header_cart,
            'total_cart_price': total_cart_price,
        }

        base_products = Product.objects.get_by_categories(category_title=main_category.title)
        if sub_category_slug is not None:

            # sub Category Start:
            sub_category = Product_SubCategories.objects.filter(slug__exact=sub_category_slug)
            if sub_category.count() > 0:
                sub_category = sub_category.first()
                self.extra_context['sub_category'] = sub_category
                base_products = Product.objects.get_by_sub_categories(sub_category_title=sub_category.title)
                self.extra_context['found_product_count'] = base_products.count()
            else:
                raise Http404("صفحه مورد نظر یافت نشد")
            # sub Category END:

        # Category Start:
        if base_products.count() > 0:
            self.extra_context['db_max_price'] = base_products.order_by('-price').first().price
        else:
            self.extra_context['db_max_price'] = 0

        if not price_filter:
            return base_products
        else:
            final_query = base_products.filter(price__gte=start_price, price__lte=end_price)
            self.extra_context['found_product_count'] = final_query.count()
            self.extra_context['filter_view'] = True
            self.extra_context['start_price'] = start_price
            self.extra_context['end_price'] = end_price
            return final_query


# (-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-) SEARCH AND TAG VIEW (-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)
# (-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-) SEARCH AND TAG VIEW (-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)(-)

class Products_SearchAndTag_View(ListView):
    template_name = "ProductsListLayout.html"
    paginate_by = 10

    def get_queryset(self):

        query = self.request.GET.get('q')  # search-query request
        # s_settings = site_settings.objects.first()
        # all_categories: ProductCategories = ProductCategories.objects.all()
        # main_order_cart = giveme_cart(self.request)
        self.extra_context = {
            # 'main_order_cart': main_order_cart,
            # 'site_settings': s_settings,
            'main_category': query,
            # 'category_bar': all_categories,
            'found_product_count': 0,
            # 'is_it_in_search': True,
            'q': query,
        }

        # lvl.1 : Filter products according to requested q "search"
        if (query is not None) and (query != 'None'):
            found_products = Product.objects.search(query)
        else:
            # if search-query is not requested then > found_products = all active products
            found_products = Product.objects.get_active_products()

        # category filter
        try:
            category_slug = self.kwargs["main_category"]
        except KeyError:
            category_slug = None
        try:
            sub_category_slug = self.kwargs["sub_category"]
        except KeyError:
            sub_category_slug = None

        sub_category = Product_SubCategories.objects.filter(slug=sub_category_slug)
        main_category = ProductCategories.objects.filter(slug=category_slug)

        if sub_category.count() > 0:
            sub_category = sub_category.first()
        else:
            sub_category = None
        if main_category.count() > 0:
            main_category = main_category.first()
        else:
            main_category = None

        self.extra_context['sub_category'] = sub_category
        self.extra_context['main_category'] = main_category

        if sub_category:
            found_products = Product.objects.filter(sub_categories=sub_category)
        elif main_category:
            found_products = Product.objects.filter(categories=main_category)

        if found_products:
            self.extra_context['db_max_price'] = found_products.order_by('-price').first().price
        else:
            self.extra_context['db_max_price'] = 0

        # process the sort request
        try:
            sort_req = self.request.GET.get('sort_order')
            if sort_req is not None:
                if sort_req == 'cheapest-tab':
                    found_products = found_products.order_by('price')
                    self.extra_context['sort_order'] = "cheapest-tab"
                elif sort_req == 'most-expensive-tab':
                    found_products = found_products.order_by('-price')
                    self.extra_context['sort_order'] = "most-expensive-tab"
                elif sort_req == 'newest-tab':
                    found_products = found_products.order_by('-added_date')
                    self.extra_context['sort_order'] = "newest-tab"
        except KeyError:
            pass

        # check the filter-request (it comes with ajax request)
        if is_ajax(self.request):
            self.template_name = "Component/AjaxProductsList.html"
            self.extra_context['filter_view'] = True
            # price filter
            filter_price = self.request.GET.get('price_limit').split(' - ')
            start_price = int(filter_price[0].replace(',', ''))
            end_price = int(filter_price[1].replace(',', ''))
            self.extra_context['start_price'] = start_price
            self.extra_context['end_price'] = end_price
            found_products = found_products.filter(price__gte=start_price, price__lte=end_price)
        else:
            self.extra_context['filter_view'] = False

        # هیچ درخواستی برای فیلتر قیمت نداریم
        if found_products.count() > 0:
            self.extra_context['found_product_count'] = found_products.count()
        else:
            self.extra_context['found_product_count'] = 0
        return found_products


# ---------------------------------------------------------------- Detail View

def product_detail_view(req, p_id, **kwargs):
    the_product = give_me_the_product_by_id(p_id)
    if the_product is None:
        raise Http404("محصول مورد نظر یافت نشد")
    the_product.visit_counter += 1
    the_product.save()
    the_user = req.user if req.user.is_authenticated else None
    s_settings = site_settings.objects.first()

    # start from here ------------------

    # 1. get quantity of product in the user's cart
    main_order_cart = giveme_cart(req)
    found_product_quantity = main_order_cart.get_amount_of_product_in_cart(the_product=the_product)

    # 2. find the categories of product for showing category links
    main_category = ProductCategories.objects.filter(product=the_product)
    main_category = main_category.first() if main_category.count() else None
    sub_category = Product_SubCategories.objects.filter(product=the_product)
    sub_category = sub_category.first() if sub_category.count() else None

    # 3. new order_form
    # اینشیال ها رو اگر با نام فیلد تغییر بدیم والیو اون فیلد تغییر میکنه اگر نه باید توی فرم آپدیت بزنی
    order_form = add_order_form(req.POST or None, initial={

module_products/templates/ProductDetailLayout.html
{% extends "shared/MainLayout.html" %}
{% load static %}

{% block header_extra_ref %}
    <link rel="stylesheet" href="{% static "" %}css/plugins/noUISlider.min.css">
    <link rel="stylesheet" href="{% static "" %}css/plugins/light-zoom.min.css">
    <link rel="stylesheet" href="{% static "" %}css/plugins/magnific-popup.css">
    <link rel="stylesheet" href="{% static "" %}css/plugins/bootstrap-slider.min.css">
    <link rel="stylesheet" href="{% static "" %}css/plugins/swiper-bundle.min.css">
{% endblock %}

{% block content %}
    <!-- content -->
    <main class="content">
        <div class="single-product">
            <div class="container">
                <nav aria-label="breadcrumb" class="breadcrumb-nav">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">خانه</a></li>
                        {% if main_category %}
                            <li class="breadcrumb-item" aria-current="page">
                                 <a href="{% url "module_products:urls_products_list" main_category.slug %}">{{ main_category.title }}</a>
                            </li>
                        {% endif %}
                        {% if sub_category %}
                            <li class="breadcrumb-item" aria-current="page">
                                <a href="{% url "module_products:urls_product_list_sub_category" main_category.slug sub_category.slug %}">{{ sub_category.title }}</a>
                            </li>
                        {% endif %}
                    </ol>
                </nav>


                <div class="product type-product">
                    <div class="row">
                        <!-- Gallery -->
                        <div class="col-lg-7 col-md-7 col-xs-12">
                            {% include "Component/ProductDetailGallery.html" with product=the_product %}
                        </div>
                        <div class="col-lg-5 col-md-5 col-xs-12">
                            <div class="product-info">





{#                                <form method="post" action="{% url "module_orders:urls_cart" %}">#}
                                <form method="post" action="#">
                                    {% csrf_token %}
                                    <div class="product-headline">
                                        <h1 class="product-title"> {{ product.title }}
    {#                                    <span class="sub-head">Apple iPhone 12 A2404 Dual SIM 128GB Mobile Phone</span>#}
                                        </h1>
                                    </div>
                                    <div class="product-meta">
                                        <span class="posted">
                                            <span class="detail-label">دسته : </span>
                                            <span class="detail-content">
                                                {% if main_category %}
                                                    <a href="{% url "module_products:urls_products_list" main_category.slug %}">
                                                        {{ main_category.title }}
                                                    </a>
                                                {% else %}
                                                    بدون دسته بندی
                                                {% endif %}

                                                {% if sub_category and main_category%}
                                                ,
                                                    <a href="{% url "module_products:urls_product_list_sub_category" main_category.slug sub_category.slug %}">{{ sub_category.title }}</a>
                                                {% endif %}

                                            </span>
                                        </span>
                                    </div>
                                    <div class="price">
    {#                                    <del>#}
    {#                                        <span class="price-amount">{{ product.price }}#}
    {#                                            <span class="price-currencySymbol">تومان</span>#}
    {#                                        </span>#}
    {#                                    </del>#}
                                        <ins>
                                            {% if the_product.stock > 0 %}
                                                <span class="price-amount">{{ the_product.get_price_with_comma }}
                                                    <span class="price-currencySymbol">تومان</span>
                                                </span>
                                            {% else %}
                                                <span class="price-amount">ناموجود</span>
                                            {% endif %}
                                        </ins>
                                    </div>
                                    {{ order_form.product_id }}
                                    <div class="add-to-cart">
                                        <div class="quantity">
{#                                            <input type="number" min="1" max="{{ product.stock }}" step="1" value="1">#}
                                            {{ order_form.order_count }}
                                            {% if the_product.stock > 0 %}<div class="quantity-nav"></div>{% endif %}
                                        </div>
                                        {% if the_product.stock > 0 %}
                                            <button type="button" class="btn btn-success add-to-cart-btn" id="btn_add_to_cart" onclick="add_to_cart({{ the_product.id }}, this.id)">
                                                <i class="fal fa-cart-arrow-down"></i>
                                                افزودن به سبد خرید
                                            </button>
                                        {% else %}
                                            <button type="button" disabled class="btn btn-danger add-to-cart-btn" id="btn_add_to_favorites">
                                                <i class="fal fa-cart-arrow-down"></i>
                                                ناموجود
                                            </button>
                                        {% endif %}

{#                                       For admin#}
                                        {% if request.user.is_superuser %}
                                            <a class="btn btn-outline-dark add-to-cart-btn" href="{% url "admin_product_editor" the_product.id %}">
                                                <i class="fal fa-tools"></i>
                                                ویرایش‌ محصول
                                            </a>
                                        {% endif %}
                                    </div>
                                </form>




                            </div>
                            <div class="product-seller-info">
                                <hr>
                                <div class="product-seller-row">
                                    <div class="product-stock">
                                        {% if the_product.stock > 0 %}
                                            <i class="fal fa-check-square"></i>
                                            <span> موجود است (تعداد موجود در انبار {{ the_product.stock }})</span>
                                        {% else %}
                                            <i class="fal fa-exclamation-circle" style="color: red"></i>
                                            <span>ناموجود</span>
                                        {% endif %}
                                    </div>
                                </div>
                                {% if the_product.stock > 0 %}
                                    <div class="product-seller-row">
                                        <span class="lead-time-ready">
                                            <i class="fal fa-truck-loading"></i>
                                            آماده ارسال
                                        </span>
                                    </div>
                                {% endif %}
                                <div class="product-actions">
                                    <div class="add-to-wishlist fl">
                                        <a href="#" id="wish_a_{{ the_product.id }}" onclick="add_to_wishlist({{ the_product.id }}, this.id)" class="btn btn-light wishlist{% if request.user in the_product.wisher_users.all %} active{% endif %}">
                                            <i id="wish_fa_{{ the_product.id }}" class="fal fa-heart"></i>
                                            لیست علاقه مندی
                                        </a>
                                    </div>
                                </div>
                                <br>
                                <div class="product-feature">
                                    <div class="service-item">
                                        <img src="{% static "" %}images/service/price-tag-1.png" alt="service">
                                        بهترین قیمت
                                    </div>
                                    <div class="service-item">
                                        <img src="{% static "" %}images/service/box.png" alt="service">
                                        ارسال محصول مطابق تصویر
                                    </div>
                                    <div class="service-item">
                                        <img src="{% static "" %}images/service/delivery-truck-3.png" alt="service">
                                        ارسال رایگان بالای {{ site_settings.get_transport_limit_price_with_comma }} تومان
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Tabs -  Comments - Description -->
                    {% include "Component/ProductDetailTabs.html" with product=the_product %}
                </div>

            </div>
        </div>
    </main>
    <!-- content -->
{% endblock %}

{% block footer_extra_ref %}
    <script src="{% static "" %}js/plugins/swiper-bundle.min.js"></script>
    <script src="{% static "" %}js/plugins/theia-sticky-sidebar.min.js"></script>
    <script src="{% static "" %}js/plugins/nouislider.min.js"></script>
    <script src="{% static "" %}js/plugins/wNumb.js"></script>
    <script src="{% static "" %}js/plugins/lightzoom.min.js"></script>
    <script src="{% static "" %}js/plugins/jquery.magnific-popup.min.js"></script>
    <script src="{% static "" %}js/plugins/bootstrap-slider.min.js"></script>
    <script src="{% static "" %}js/plugins/ajax-product-detail.js"></script>
    <script src="{% static "" %}js/plugins/ajax_add_to_favorites_and_cart.js"></script>
{% endblock %}

module_products/templates/ProductsListLayout.html
{% extends "shared/MainLayout.html" %}
{% load static %}

{% block header_extra_ref %}
    <link rel="stylesheet" href="{% static "" %}css/plugins/noUISlider.min.css">
{% endblock %}



{% block content %}
    <!-- content -->
    <main class="content mt-3">
        <div class="container" id="container">
            <nav aria-label="breadcrumb" class="breadcrumb-nav">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">خانه</a></li>
                    {% if main_category.slug %}
                        <li class="breadcrumb-item" aria-current="page">
                            <a href="{% url "module_products:urls_products_list" main_category.slug %}">{{ main_category.title }}</a>
                        </li>
                    {% else %}
                        <li class="breadcrumb-item" aria-current="page">
                            <a href="{% url "module_products:urls_products_search_tag"%}?q={{ main_category }}">{{ main_category }}</a>
                        </li>
                    {% endif %}
                    {% if sub_category %}
                        <li class="breadcrumb-item" aria-current="page">
                            <a href="{% url "module_products:urls_product_list_sub_category" main_category.slug sub_category.slug %}">{{ sub_category.title }}</a>
                        </li>
                    {% endif %}
                </ol>
            </nav>

            <div id="ajax_products_list">
                {% include "Component/AjaxProductsList.html" %}
            </div>


        </div>
    </main>
    <!-- content -->
{% endblock %}




{% block footer_extra_ref %}
<script src="{% static "" %}js/plugins/theia-sticky-sidebar.min.js"></script>
<script src="{% static "" %}js/plugins/nouislider.min.js"></script>
<script src="{% static "" %}js/plugins/wNumb.js"></script>

<script>
    //    price-range Desktop
    var nonLinearStepSlider = document.getElementById('slider-non-linear-step');
    if ($('#slider-non-linear-step').length) {
        noUiSlider.create(nonLinearStepSlider, {
            start: [0, {{ db_max_price }}],
            connect: true,
            direction: 'rtl',
            format: wNumb({
                decimals: 0,
                thousand: ','
            }),
            range: {
                'min': [0],
                '10%': [1000, 1000],
                {#'50%': [40000, 1000],#}
                'max': [{{ db_max_price }}]
            }
        });
        var nonLinearStepSliderValueElement = document.getElementById('slider-non-linear-step-value');

        nonLinearStepSlider.noUiSlider.on('update', function (values) {
            nonLinearStepSliderValueElement.innerHTML = values.join(' - ');
        });
    }
    //    price-range Mobile
    var nonLinearStepSlider2 = document.getElementById('slider-non-linear-step2');
    if ($('#slider-non-linear-step2').length) {
        noUiSlider.create(nonLinearStepSlider2, {
            start: [0, {{ db_max_price }}],
            connect: true,
            direction: 'rtl',
            format: wNumb({
                decimals: 0,
                thousand: ','
            }),
            range: {
                'min': [0],
                '10%': [1000, 1000],
                {#'50%': [40000, 1000],#}
                'max': [{{ db_max_price }}]
            }
        });
        var nonLinearStepSliderValueElement2 = document.getElementById('slider-non-linear-step-value2');

        nonLinearStepSlider2.noUiSlider.on('update', function (values) {
            nonLinearStepSliderValueElement2.innerHTML = values.join(' - ');
        });
    }
</script>

    <script src="{% static "" %}js/plugins/ajax_add_to_favorites_and_cart.js"></script>
    <script src="{% static "" %}js/plugins/ajax_products_filter.js"></script>

{% endblock %}