module_contact/urls.py
from django.urls import path
from .views import contact_view

urlpatterns = [
    path('', contact_view, name="urls_contact-us_view"),
]

app_name = "module_contact-us"

module_orders/urls.py
from django.urls import path
from .views import orders_cart_view, ajax_delete_from_cart, ajax_delete_from_sidebar, ajax_change_amount, checkout_view, ajax_add_to_cart
from .payment_verify_views import verify_payment_view

urlpatterns = [
    path('cart', orders_cart_view, name="urls_cart"),

    # ajax_delete from cart page
    path('cart/ajax/c-delete/', ajax_delete_from_cart, name="urls_ajax_delete_cart_page_item"),

    # ajax_delete from sidebar cart
    path('cart/ajax/s-delete/', ajax_delete_from_sidebar, name="urls_ajax_delete_side_cart_item"),

    path('cart/json/amount/', ajax_change_amount, name="urls_ajax_change_amount"),

    path('checkout/', checkout_view, name="urls_checkout"),
    path('checkout/<repay_cart_id>', checkout_view, name="urls_checkout_repay"),

    path('verify/', verify_payment_view, name="urls_verify_payment"),
    path('verify/<cart_id>', verify_payment_view, name="urls_verify_payment_callback"),


    path('ajax/add_to_cart/', ajax_add_to_cart, name="urls_ajax_add_to_cart"),
]


app_name = "module_orders"

module_profile/urls.py
from django.urls import path
from .views import profile_view, profile_address_edit, \
    profile_address_edit_ajax_view, orders_list_view, order_detail, wishlist_view, edit_profile_view, seller_main_view

urlpatterns = [
    path('dashboard', profile_view, name="urls_profile_view"),

    path('address_edit/', profile_address_edit, name="urls_profile_address_edit"),
    path('address_edit/ajax/', profile_address_edit_ajax_view, name="urls_profile_address_edit_ajax"),

    path('orders_history/', orders_list_view, name="urls_profile_orders_history"),
    path('orders_list/detail/<order_id>', order_detail, name="urls_profile_order_detail"),

    path('wishlist', wishlist_view, name="urls_profile_wishlist"),

    path('edit_profile/', edit_profile_view, name="urls_profile_edit_profile"),

    path('seller/', seller_main_view, name="urls_profile_seller_main"),

]


app_name = "module_profile"

module_users/urls.py
from django.urls import path
from .views import log_out_view
from .views import login_view, ajax_email_phone, ajax_password, ajax_otp, ajax_otp_reset, ajax_register

urlpatterns = [
    path('login/', login_view, name="urls_Login_Page"),
    path('login/email-phone/', ajax_email_phone, name="urls_ajax_email_phone"),

    path('login/ajax_password/', ajax_password, name="urls_ajax_password"),
    path('login/ajax_otp/', ajax_otp, name="urls_ajax_otp"),
    path('login/ajax_otp_reset/', ajax_otp_reset, name="urls_ajax_otp_reset"),  # Do not change (used in layout)
    path('login/ajax_register/', ajax_register, name="urls_ajax_register"),

    path('logout', log_out_view, name="urls_Logout"),
]


app_name = "module_users"

termos_eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_page, about_us_view, terms_view, sys_view, admin_links

# to use assets
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home_page, name="urls_Home_Page"),
    path('about-us', about_us_view, name="urls_about_us"),
    path('terms-conditions', terms_view, name="urls_terms"),
    # path('', AjaxHandlerView.as_view(), name="urls_Home_Page"),
    path('user/', include("module_users.urls", namespace="module_users")),
    path('products/', include("module_products.urls", namespace="module_products")),
    path('orders/', include("module_orders.urls", namespace="module_orders")),
    path('profile/', include("module_profile.urls", namespace="module_profile")),
    path('product_comments/', include("module_product_comments.urls", namespace="product_comments")),
    path('contact-us/', include("module_contact.urls", namespace="module_contact-us")),


    path('sys', sys_view, name="urls_sys"),


    path('termos_admin_panel/', admin.site.urls),
    path('edit_product/<p_id>', admin_links, name="admin_product_editor"),
]


if settings.DEBUG:
    # add root static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

module_orders/forms.py
from django import forms
from django.http import Http404
from module_products.models import Product
from module_orders.models import Order_Detail_Model

# خیلیم راحته


class add_order_form(forms.Form):
    product_id = forms.CharField(widget=forms.HiddenInput())
    order_count = forms.IntegerField(min_value=0, widget=forms.NumberInput(attrs={'step': '1', 'value': '1'}))

    # def give_me_count(self):
    #     return self.fields['order_count']

    class Meta:
        model = Product
        fields = 'stock'

    # __init__ will be run when make new object as this class
    def __init__(self, *args, **kwargs):
        if len(kwargs.items()) != 0:
            kw = kwargs['initial']
            the_product = kw['the_product']
            # the_user = kw['the_user']
            in_cart_qty = kw['found_product_count']
            if the_product:
                # the_product = Product.objects.filter(id=pid)
                # if the_product.count() != 1:
                #     raise Http404("صفحه مورد نظر یافت نشد")
                # the_product = the_product.first()
                start_val = the_product.stock - in_cart_qty
                min_val = 1
                if start_val > 0:
                    start_val = 1
                else:
                    start_val = 0
                    min_val = 0
                super(add_order_form, self).__init__(*args, **kwargs)
                self.fields['order_count'].widget.attrs.update({'max': (the_product.stock-in_cart_qty), 'value': start_val, 'min': min_val})
                self.fields['product_id'].widget.attrs.update({'value': the_product.id})


def how_many_in_cart(the_product, username):
    user_cart = Order_Detail_Model.objects.filter(from_Main_order__owner__username=username, from_Main_order__is_paid=False, product=the_product)
    if user_cart.count() == 1:
        return user_cart.first().count
    else:
        return 0

module_orders/views.py
import module_users.models
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from termos_eshop.views import partial_sidebar_cart_view
from module_SiteSettings.models import site_settings
from module_profile.views import profile_address_edit
from django.urls import reverse
from termos_eshop.Utilities import giveme_cart, \
    create_new_or_update_product_in_cart, give_me_the_product_by_id
from module_orders.models import Order_Main_Model, Order_Detail_Model
from termos_eshop.Utilities import is_ajax, bad_request_ajax_error, get_user_address, get_site_settings
from .payment_verify_views import verify_payment_view
from termos_eshop.Utilities import delete_product_from_cart


def orders_cart_view(req):
    cont = {'site_settings': get_site_settings()}
    # cont = giveme_site_settings_and_category(cont)
    main_order_cart = giveme_cart(req)

    # check that if user has main_Order with Detail_order (cart with products in)
    is_user_has_active_cart_to_show = is_it_filled_cart(req=req, cart=main_order_cart)

    if is_user_has_active_cart_to_show:
        # check it to send main_order_cart or session_cart_items
        if req.user.is_authenticated:
            cont['main_order_cart'] = main_order_cart
            s_settings = cont['site_settings']
            if s_settings.transport_limit:
                if main_order_cart.get_total_price() >= int(s_settings.transport_limit_price):
                    cont['transport_price'] = 0
                else:
                    cont['transport_price'] = int(s_settings.transport_price)
            else:
                cont['transport_price'] = 0
        else:
            # session_cart_items
            cont['session_cart_items'] = main_order_cart
    else:
        #  show the empty Cart
        cont['main_order_cart'] = None

    return render(req, "CartLayout.html", cont)


# --------------------------------------------------- CHECKOUT ---------------------------------------------------
# --------------------------------------------------- CHECKOUT ---------------------------------------------------


@login_required(login_url="/user/login")  # 11/9/2022 m/d/y
def checkout_view(req, **kwargs):

    #  Utilities for process
    cont = {}
    cart_id_for_repay = kwargs.get('repay_cart_id')

    # is user requested to repay an already paid cart ?
    if cart_id_for_repay:
        order_for_repay = Order_Main_Model.objects.filter(id=cart_id_for_repay,
                                                          owner_id=req.user.id,
                                                          is_paid=True,
                                                          payment_status=1)
        if order_for_repay.count() == 1:
            order_for_repay = order_for_repay.first()
        else:
            return redirect("module_orders:urls_cart")
    else:
        order_for_repay = None

    # ////////// ---- ////////// | ////////// ---- //////////

    if req.method == "POST":  # payment_page requested
        if req.POST.get('accept_terms'):  # terms are accepted > goto payment page

            if order_for_repay:
                # goto payment page for unsuccessful paid cart
                return verify_payment_view(request=req, repay_cart_id=order_for_repay.id)
            else:
                # goto payment page for current(unpaid) cart
                return verify_payment_view(req)

        else:
            # show message to accept terms
            cont['force_terms'] = True

    # ////////// ---- ////////// | ////////// ---- //////////

    # show the checkout Page ---------------------------------

    the_address = get_user_address(req)

    # if user address is not completely filled > send user to edit_address page
    if not is_it_perfect_address(the_address):
        return profile_address_edit(req, Referer=reverse("module_orders:urls_checkout"))

    # if user requested to repay an already_paid_cart, then we have to render it else > render current cart
    main_order_cart = giveme_cart(req) if not order_for_repay else order_for_repay

    if main_order_cart.get_amount() == 0:
        # Cart is empty > redirect to cart page
        return redirect("module_orders:urls_cart")

    cont['main_order_cart'] = main_order_cart
    cont['site_settings'] = get_site_settings()

    return render(req, "Checkout.html", cont)


# ---------------------------------------- DELETE Views ----------------------------------------
# ---------------------------------------- DELETE Views ----------------------------------------


# Delete Product from cart page
def ajax_delete_from_cart(req):
    if is_ajax(req):

        # receive request parameters and find the_product
        product_id = req.POST.get('product_id')
        the_product = give_me_the_product_by_id(product_id)
        if the_product is None:
            return bad_request_ajax_error()

        # delete the_product from cart
        delete_product_from_cart(req=req, the_product=the_product)
        main_order_cart = giveme_cart(req)

        # process Start
        if req.user.is_authenticated:
            products_in_cart = Order_Detail_Model.objects.filter(from_Main_order=main_order_cart)

            if products_in_cart.count() == 0:
                # show empty cart
                outer = """
                    <div class="checkout">
                        <div class="form-coupon-toggle">
                            <div class="woocommerce-info">
                                سبد خرید شما خالی است
                            </div>
                        </div>
                    </div>
                """
                response = {'outer': outer, 'amount_of_cart_products': '0'}
            else:
                # show the remained products
                cont = {'site_settings': site_settings.objects.first(), 'main_order_cart': main_order_cart}
                outer = render_to_string(request=req, template_name="includes/CartWithProducts.html", context=cont)
                response = {'outer': outer, 'amount_of_cart_products': main_order_cart.get_amount()}

            return JsonResponse(response, status=200)
        else:
            # User is not logged in >> delete it from sessions
            if main_order_cart.number_of_cart_items:
                # send the response
                cont = {'site_settings': site_settings.objects.first(), 'session_cart_items': main_order_cart}
                outer = render_to_string(request=req, template_name="includes/CartWithProducts.html", context=cont)
                response = {'outer': outer, 'amount_of_cart_products': main_order_cart.number_of_cart_items}
            else:
                outer = """
                    <div class="checkout">
                        <div class="form-coupon-toggle">
                            <div class="woocommerce-info">
                                سبد خرید شما خالی است
                            </div>
                        </div>
                    </div>
                """
                response = {'outer': outer, 'amount_of_cart_products': '0'}

            return JsonResponse(response, status=200)
    return bad_request_ajax_error()


# @csrf_protect
# @login_required(login_url="/user/login")
#  this function is for deleting products from sidebar cart
def ajax_delete_from_sidebar(req):  # 11/04/2022  - m/d/y
    if is_ajax(req):
        # receive request parameters and find the_product
        try:
            product_id = req.POST.get('product_id')
        except KeyError:
            return bad_request_ajax_error()
        the_product = give_me_the_product_by_id(product_id)
        if the_product is None:
            return bad_request_ajax_error()

        # delete the_product from user's cart
        delete_product_from_cart(req, the_product)
        main_order_cart = giveme_cart(req)

        if req.user.is_authenticated:
            outer = partial_sidebar_cart_view(req, render_to_str=True)
            response = {
                'outer': outer,
                'amount_of_cart_products': main_order_cart.get_amount(),
            }
            return JsonResponse(response, status=200)
        else:
            outer = partial_sidebar_cart_view(req, render_to_str=True)
            response = {
                'outer': outer,
                'amount_of_cart_products': main_order_cart.number_of_cart_items,
            }
            return JsonResponse(response, status=200)
    else:
        return bad_request_ajax_error()


# ---------------------------------------- CHANGE COUNT View ----------------------------------------
# ---------------------------------------- CHANGE COUNT View ----------------------------------------

def ajax_change_amount(req):
    if is_ajax(req):
        # receive request parameters and find the_product
        try:
            order_count = req.POST.get('product_count')
            product_id = req.POST.get('product_id')
        except KeyError:
            return bad_request_ajax_error()
        the_product = give_me_the_product_by_id(product_id)
        if the_product is None:
            return bad_request_ajax_error()

        try:
            if int(order_count) <= 0:  # if ther product need to be deleted (requested to amount = 0)
                return ajax_delete_from_cart(req)
        except ValueError:
            return bad_request_ajax_error()

        main_cart = giveme_cart(req)

        if req.user.is_authenticated:
            #  user is logged in - procces on database
            detail_cart, out_of_stock = create_new_or_update_product_in_cart(req=req, order_main=main_cart,
                                                                             order_count=order_count,
                                                                             the_product=the_product, append=False)

module_orders/templates/orders_payments/PaymentFailed.html
{% extends "shared/MainLayout.html" %}
{% load static %}

{% block content %}
    <main class="content">
        <div class="container">
            <div class="order-steps">
                <div class="checkout-breadcrumb">
                    <div class="title-cart">
                        <i class="fal fa-bags-shopping"></i>
                        <a>
                            <h4>سبد خرید</h4>
                        </a>
                    </div>
                    <div class="title-checkout">
                        <i class="fal fa-file-invoice"></i>
                        <a>
                            <h4>جزئیات پرداخت</h4>
                        </a>
                    </div>
                    <div class="title-thankyou">
                        <i class="fal fa-receipt"></i>
                        <a>
                            <h4>تکمیل سفارش</h4>
                        </a>
                    </div>
                </div>
            </div>
            <div class="checkout">
                <div class="text-center">
                    <div class="icon-success warning">
                        <i class="fal fa-exclamation-triangle"></i>
                    </div>
                    <div class="order-success">
                        <div class="h4 font-weight-bold mb-4">ثبت سفارش شما با موفقیت انجام نشد</div>
                        <div class="font-weight-bold mb-12">چنانچه طی این فرایند مبلغی از حساب شما کسر شده است،طی 72 ساعت آینده به حساب شما باز خواهد گشت.</div>
                        {% if message %}
                            <hr>
                            <span class="alert-danger">پیام دریافتی از درگاه پرداخت : {{ message }}</span>
                        {% endif %}
                    </div>
                    <div class="order-actions">

                        {% if card_id %}  {#  if card payment is failed by error and card_is_paid=True #}
                            <a href="{% url "module_orders:urls_checkout_repay" cart_id %}" class="btn btn-secondary btn-order-tracking">
                        {% else %} {# if card_payment is cancelled by user and the card kept as current_active cart #}
                            <a href="{% url "module_orders:urls_checkout" %}" class="btn btn-secondary btn-order-tracking">
                        {% endif %}

                            <i class="fa fa-repeat"></i>
                            پرداخت مجدد
                        </a>
                        <a href="{% url "module_contact-us:urls_contact-us_view" %}" class="btn btn-danger btn-order-tracking btn-contact-backup"><i class="fa fa-phone"></i>
                            تماس با پشتیبان
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

module_orders/templates/orders_payments/PaymentSuccess.html
{% extends "shared/MainLayout.html" %}
{% load static %}

{% block content %}
    <!-- content -->
    <main class="content">
        <div class="container">
            <div class="order-steps">
                <div class="checkout-breadcrumb">
                    <div class="title-cart">
                        <i class="fal fa-bags-shopping"></i>
                        <a>
                            <h4>سبد خرید</h4>
                        </a>
                    </div>
                    <div class="title-checkout">
                        <i class="fal fa-file-invoice"></i>
                        <a>
                            <h4>جزئیات پرداخت</h4>
                        </a>
                    </div>
                    <div class="title-thankyou">
                        <i class="fal fa-receipt"></i>
                        <a>
                            <h4>تکمیل سفارش</h4>
                        </a>
                    </div>
                </div>
            </div>
            <div class="checkout">
                <div class="text-center">
                    <div class="icon-success">
                        <i class="fal fa-check"></i>
                    </div>
                    <div class="order-success">
                        <div class="h4 font-weight-bold mb-4">پرداخت با موفقیت انجام شد</div>
                        <div class="font-weight-bold mb-12">سفارش شما ثبت شد و به زودی پردازش خواهد شد. شما میتوانید در بخش پنل کاربری وضعیت سفارش‌ها خود را مشاهده نمایید</div>
                    </div>
                    <div class="order-actions">
                        <a href="{% url "module_profile:urls_profile_order_detail" order_id %}" class="btn btn-primary btn-order-tracking">
                            <i class="fal fa-shopping-bag"></i>
                            پیگیری سفارش
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!-- content -->
{% endblock %}