module_orders/urls.py
from django.urls import path
from .views import orders_cart_view, ajax_delete_from_cart, ajax_delete_from_sidebar, ajax_change_amount, checkout_view, ajax_add_to_cart
from .payment_verify_views import verify_payment_view

urlpatterns = [
    path('cart', orders_cart_view, name="urls_cart"),

    # ajax_delete from cart page
    path('cart/ajax/c-delete/', ajax_delete_from_cart, name="urls_ajax_delete_cart_page_item"),

    # ajax_delete from sidebar cart
    path('cart/ajax/s-delete/', ajax_delete_from_sidebar, name="urls_ajax_delete_side_cart_item"),

    path('cart/json/amount/', ajax_change_amount, name="urls_ajax_change_amount"),

    path('checkout/', checkout_view, name="urls_checkout"),
    path('checkout/<repay_cart_id>', checkout_view, name="urls_checkout_repay"),

    path('verify/', verify_payment_view, name="urls_verify_payment"),
    path('verify/<cart_id>', verify_payment_view, name="urls_verify_payment_callback"),


    path('ajax/add_to_cart/', ajax_add_to_cart, name="urls_ajax_add_to_cart"),
]


app_name = "module_orders"

module_profile/urls.py
from django.urls import path
from .views import profile_view, profile_address_edit, \
    profile_address_edit_ajax_view, orders_list_view, order_detail, wishlist_view, edit_profile_view, seller_main_view

urlpatterns = [
    path('dashboard', profile_view, name="urls_profile_view"),

    path('address_edit/', profile_address_edit, name="urls_profile_address_edit"),
    path('address_edit/ajax/', profile_address_edit_ajax_view, name="urls_profile_address_edit_ajax"),

    path('orders_history/', orders_list_view, name="urls_profile_orders_history"),
    path('orders_list/detail/<order_id>', order_detail, name="urls_profile_order_detail"),

    path('wishlist', wishlist_view, name="urls_profile_wishlist"),

    path('edit_profile/', edit_profile_view, name="urls_profile_edit_profile"),

    path('seller/', seller_main_view, name="urls_profile_seller_main"),

]


app_name = "module_profile"

module_users/urls.py
from django.urls import path
from .views import log_out_view
from .views import login_view, ajax_email_phone, ajax_password, ajax_otp, ajax_otp_reset, ajax_register

urlpatterns = [
    path('login/', login_view, name="urls_Login_Page"),
    path('login/email-phone/', ajax_email_phone, name="urls_ajax_email_phone"),

    path('login/ajax_password/', ajax_password, name="urls_ajax_password"),
    path('login/ajax_otp/', ajax_otp, name="urls_ajax_otp"),
    path('login/ajax_otp_reset/', ajax_otp_reset, name="urls_ajax_otp_reset"),  # Do not change (used in layout)
    path('login/ajax_register/', ajax_register, name="urls_ajax_register"),

    path('logout', log_out_view, name="urls_Logout"),
]


app_name = "module_users"

termos_eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_page, about_us_view, terms_view, sys_view, admin_links

# to use assets
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home_page, name="urls_Home_Page"),
    path('about-us', about_us_view, name="urls_about_us"),
    path('terms-conditions', terms_view, name="urls_terms"),
    # path('', AjaxHandlerView.as_view(), name="urls_Home_Page"),
    path('user/', include("module_users.urls", namespace="module_users")),
    path('products/', include("module_products.urls", namespace="module_products")),
    path('orders/', include("module_orders.urls", namespace="module_orders")),
    path('profile/', include("module_profile.urls", namespace="module_profile")),
    path('product_comments/', include("module_product_comments.urls", namespace="product_comments")),
    path('contact-us/', include("module_contact.urls", namespace="module_contact-us")),


    path('sys', sys_view, name="urls_sys"),


    path('termos_admin_panel/', admin.site.urls),
    path('edit_product/<p_id>', admin_links, name="admin_product_editor"),
]


if settings.DEBUG:
    # add root static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

module_profile/models.py
from django.db import models

# Create your models here.

module_profile/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse, Http404
from module_orders.models import Order_Main_Model, Order_Detail_Model
from termos_eshop.Utilities import is_it_numeric, is_it_email, is_it_first_or_last_name, is_it_phone_number, is_ajax, \
    get_user_address, giveme_remaining_time_for_verify, reset_user_otp, otp_check
from module_products.models import Product
from django.shortcuts import render, redirect
from django.urls import reverse
from module_SiteSettings.models import site_settings
from termos_eshop.Utilities import bad_request_ajax_error, log_it_in
from termos_eshop.smsclass import send_otp_sms, send_products_update_sms


@login_required(login_url="/user/login")
def profile_address_edit(req, **kwargs):  # 11/9/2022 m/d/y

    get_user_address(req)  # create new address if not exist

    if req.user.is_authenticated:
        try:
            back_address = kwargs['Referer']
        except KeyError:
            try:
                back_address = req.headers['Referer']
            except KeyError:
                back_address = reverse("module_profile:urls_profile_view")

        cont = {'back_address': back_address, 'site_settings': site_settings.objects.first()}
        return render(req, "profile/AddressEditLayout/AddressEditLayout.html", context=cont)

    else:
        return redirect("module_users:urls_Login_Page")


@login_required(login_url="/user/login")
def profile_address_edit_ajax_view(req):
    if not is_ajax(req):
        return bad_request_ajax_error()
    try:
        first_name = req.POST['name'].strip()
        last_name = req.POST['last_name'].strip()
        state = req.POST['state']
        city = req.POST['city'].strip()
        address = req.POST['address'].strip()
        postcode = req.POST['postcode']
        phone = req.POST['phone'].strip()
        email = req.POST['email'].strip()
        # back_link = req.POST['back_address']
    except KeyError:
        return bad_request_ajax_error()
    error_list = check_address_form(first_name, last_name, state, city, address, postcode, phone, email)

    if not error_list['is_there_error']:
        # save address
        db_address = get_user_address(req)
        db_address.name = first_name
        db_address.family = last_name
        db_address.state = state
        db_address.city = city
        db_address.address_detail = address
        db_address.post_code = postcode
        db_address.phone = phone
        db_address.email = email
        db_address.save()
        # The process is Done

    response = {'error_list': error_list}
    return JsonResponse(response, status=200)


def check_address_form(first_name, last_name, state, city, address, postcode, phone, email):
    error_list = {
        'first_name': False, 'last_name': False, 'state': False,
        'city': False, 'address': False, 'postcode': False, 'phone': False, 'email': False, 'is_there_error': False
    }
    state = int(state)

    if (not is_it_first_or_last_name(first_name)) or first_name == '' or len(first_name) > 250 or len(first_name) < 3:
        error_list['first_name'] = True
        error_list['is_there_error'] = True

    if (not is_it_first_or_last_name(last_name)) or last_name == '' or len(last_name) > 250 or len(last_name) < 3:
        error_list['last_name'] = True
        error_list['is_there_error'] = True

    if (not is_it_numeric(state)) or state == 0 or state > 32:
        error_list['state'] = True
        error_list['is_there_error'] = True

    if (not is_it_first_or_last_name(city)) or city == '' or len(city) > 50 or len(city) < 2:
        error_list['city'] = True
        error_list['is_there_error'] = True

    if address is None or address == '' or len(address) > 250 or len(address) < 8:
        error_list['address'] = True
        error_list['is_there_error'] = True

    if (not is_it_numeric(postcode)) or len(postcode) != 10:
        error_list['postcode'] = True
        error_list['is_there_error'] = True

    if not is_it_email(email):
        error_list['email'] = True
        error_list['is_there_error'] = True

    if not is_it_phone_number(phone):
        error_list['phone'] = True
        error_list['is_there_error'] = True

    return error_list


# --------------------------------------------------------------- Profile View ----------------------------------------
# --------------------------------------------------------------- Profile View ----------------------------------------

@login_required(login_url="/user/login")
def profile_view(req):
    if User.is_authenticated and req.user.id is not None:
        # user is logged in
        user_id = req.user.id
        cont = {}
        wish_list = Product.objects.filter(wisher_users=req.user)
        cont['wish_list'] = wish_list
        cont['user_paid_orders'] = Order_Main_Model.objects.filter(owner_id=user_id, is_paid=True)
        cont['site_settings'] = site_settings.objects.first()
        return render(req, "profile/ProfileLayout/ProfileLayout.html", cont)
    else:
        return redirect("module_users:urls_Login_Page")


# --------------------------------------------------------------- OrdersList(order history) View ----------------------
# --------------------------------------------------------------- OrdersList(order history) View ----------------------
@login_required(login_url="/user/login")
def orders_list_view(req):
    # we need all main maincarts(header_cart)
    if User.is_authenticated and req.user.id is not None:
        # user is logged in
        user_id = req.user.id
        main_cart = Order_Main_Model.objects.filter(owner_id=user_id, is_paid=True)
        cont = {
            'header_cart': main_cart,
            'site_settings': site_settings.objects.first(),
        }
        return render(req, "profile/OrdersLayouts/OrdersLayout.html", cont)
    else:
        return redirect("module_users:urls_Login_Page")


# --------------------------------------------------------------- Order Detail ----------------------------------------
# --------------------------------------------------------------- Order Detail ----------------------------------------


@login_required(login_url="/user/login")
def order_detail(req, order_id):
    main_order = Order_Main_Model.objects.filter(id=order_id, owner_id=req.user.id, is_paid=True)
    if main_order.count() != 1:
        raise Http404("صفحه مورد نظر یافت نشد 1010")
    main_order = main_order.first()
    detail_orders = Order_Detail_Model.objects.filter(from_Main_order=main_order)
    cont = {'detail_orders': detail_orders, 'main_order': main_order, 'site_settings': site_settings.objects.first()}

    return render(req, "profile/OrdersLayouts/OrderDetailLayout.html", cont)


# --------------------------------------------------------------- Wishlist View ---------------------------------------
# --------------------------------------------------------------- Wishlist View ---------------------------------------


@login_required(login_url="/user/login")
def wishlist_view(req):
    cont = {'wish_list': Product.objects.filter(wisher_users=req.user)}

    return render(req, "profile/Wishlist/Wishlist.html", cont)


# --------------------------------------------------------------- Edit Profile View -----------------------------------
# --------------------------------------------------------------- Edit_profile View -----------------------------------


@login_required(login_url="/user/login")
def edit_profile_view(req):  # 12/05/22  m/d/y
    if is_ajax(req):
        try:
            first_name = req.POST['first_name'].strip()
            last_name = req.POST['last_name'].strip()
            email = req.POST['email'].strip()
            phone = req.POST['phone'].strip()
            new_password = req.POST['new_pass'].strip()
            verify_code = req.POST['verify_code'].strip()
            in_verify_form = req.POST['in_verify_form']
        except KeyError:
            return bad_request_ajax_error()

        # Options
        error_list = {
            'first_name': False, 'last_name': False,
            'email': False, 'phone': False,
            'new_pass': False, 'verify_code': False,
            'wait_message': False
        }
        has_it_error = False

        # check Inputs
        if not is_it_first_or_last_name(first_name):
            error_list['first_name'] = True
            has_it_error = True
        if not is_it_first_or_last_name(last_name):
            error_list['last_name'] = True
            has_it_error = True

        if not is_it_email(email):
            error_list['email'] = True
            has_it_error = True
        elif User.objects.filter(email__exact=email).count():
            for found_user in User.objects.filter(email__exact=email).all():
                if found_user != req.user:
                    error_list['email'] = True
                    has_it_error = True

        if not is_it_phone_number(phone):
            error_list['phone'] = True
            has_it_error = True
        elif User.objects.filter(useradditional__Phone=phone).count():
            for found_user in User.objects.filter(useradditional__Phone=phone).all():
                if found_user != req.user:
                    error_list['phone'] = True
                    has_it_error = True

        if new_password is not None and new_password != '':
            if len(new_password) < 8 or len(new_password) > 50:
                error_list['new_pass'] = True
                has_it_error = True
        if is_it_numeric(verify_code) and len(verify_code) != 6:  # Code check lvl-1 (not empty and be 6 digits)
            error_list['verify_code'] = True
            has_it_error = True

        #  ---------------------------------------------------

        if not has_it_error:  # There is no error

            # check OTP timer

            # checking that is information changed ?!! or not

module_profile/templates/shared/_MobileSidebarComponent.html
{% load static %}
<nav class="sidebar">
    <div class="woocommerce-MyAccount-navigation">
        <div class="my-account-info">
            <a href="#" class="gravatar">
                <img src="{% static "" %}images/avatar/avatar.jpg" alt="avatar" class="img-fluid avatar">
            </a>
            <span class="username">{{ request.user.get_full_name }}</span>
        </div>
        <div class="my-account-menu">
            <div class="item-menu">
                <a href="{% url "urls_Home_Page" %}">
                    <i class="fal fa-store"></i>
                    صفحه اصلی ترموس
                </a>
            </div>
            <div class="item-menu">
                <a href="{% url "module_orders:urls_cart" %}">
                    <i class="fal fa-shopping-bag"></i>
                    سبد خرید
                </a>
            </div>
        </div>
        <ul>
            <li class="MyAccount-navigation-link MyAccount-navigation-link-dashboard
            {% if 'dashboard' in request.path %}
                is-active
            {% endif %} 
             ">
                <a href="{% url "module_profile:urls_profile_view" %}">
                    <i class="fal fa-tachometer"></i>
                    پیشخوان
                </a>
            </li>



            {% if request.user.useradditional.IsSeller %}
                <li class="MyAccount-navigation-link MyAccount-navigation-link-seller
                {% if 'seller' in request.path %}
                    is-active
                {% endif %}
                 ">
                    <a href="{% url "module_profile:urls_profile_seller_main" %}">
                        <i class="fal fa-bags-shopping"></i>
                            <span class="text-success">
                                محصولات من
                            </span>
                    </a>
                </li>
            {% endif %}




            <li class="MyAccount-navigation-link MyAccount-navigation-link-orders
            {% if 'orders_history' in request.path %}
                is-active
            {% endif %}
             ">
                <a href="{% url "module_profile:urls_profile_orders_history" %}">
                    <i class="fal fa-shopping-basket"></i>
                    سفارش ها
                </a>
            </li>
            <li class="MyAccount-navigation-link MyAccount-navigation-link-wishlists
            {% if 'wishlist' in request.path %}
                is-active
            {% endif %}
             ">
                <a href="{% url "module_profile:urls_profile_wishlist" %}">
                    <i id="wish_fa_{{ product.id }}" class="fal fa-heart"></i>
                    علاقه مندی ها
                </a>
            </li>
            <li class="MyAccount-navigation-link MyAccount-navigation-link-edit-address
            {% if 'address_edit' in request.path %}
                is-active
            {% endif %}
             ">
                <a href="{% url "module_profile:urls_profile_address_edit" %}">
                    <i class="fal fa-home"></i>
                    آدرس‌ ارسال سفارشات
                </a>
            </li>
            <li class="MyAccount-navigation-link MyAccount-navigation-link-edit-account
            {% if 'edit_profile' in request.path %}
                is-active
            {% endif %}
             ">
                <a href="{% url "module_profile:urls_profile_edit_profile" %}">
                    <i class="fal fa-user"></i>
                    ویرایش حساب کاربری
                </a>
            </li>
            <li class="MyAccount-navigation-link MyAccount-navigation-link-customer-logout">
                <a href="{% url "module_users:urls_Logout" %}">
                    <i class="fal fa-sign-in"></i>
                    خروج از حساب کاربری
                </a>
            </li>
        </ul>
    </div>
</nav>

module_profile/templates/shared/_ProfileMainLayout.html
{% load static %}
{% load render_partial %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {% render_partial 'termos_eshop.views.partial_title_icon_view' %}

        <!-- fontAwesome -->
        <link rel="stylesheet" href="{% static "" %}css/font-awesome.min.css">
        <!-- Bootstrap -->
        <link rel="stylesheet" href="{% static "" %}bootstrap/css/bootstrap.min.css">
        <!-- CSS Implementing Plugins -->
        <link rel="stylesheet" href="{% static "" %}css/plugins/nice-select.css">
        <link rel="stylesheet" href="{% static "" %}css/plugins/swiper-bundle.min.css">
        <link rel="stylesheet" href="{% static "" %}css/plugins/noUISlider.min.css">
        <!-- mainStyle -->
        <link rel="stylesheet" href="{% static "" %}css/main.css">
        <link rel="stylesheet" href="{% static "" %}css/responsive.css">
        {% block extraCss %}{% endblock %}
    </head>


    <body>
        <!-- content -->
        <main class="content mt-0">
            <div class="container">
                <div class="row">
                    <!-- Mobile_sidebar -->
                    {% include "shared/_MobileSidebarComponent.html" %}
                    <div class="nav-btn nav-slider nav-profile">
                        <span class="linee1"></span>
                        <span class="linee2"></span>
                        <span class="linee3"></span>
                    </div>
                    <div class="overlay"></div>
                    <div class="col-lg-3">
                        <nav class="woocommerce-MyAccount-navigation MyAccount-navigation-none">


                            <div class="my-account-info">
                                <a href="{% url "module_profile:urls_profile_view" %}" class="gravatar">
                                    <img src="{% static "" %}images/avatar/avatar.jpg" class="img-fluid avatar" alt="{{ site_settings.site_title }}">
                                </a>
                                <span class="username">{{ request.user.get_full_name }}</span>
                            </div>

                            <div class="my-account-menu">
                                <div class="item-menu">
                                    <a href="{% url "urls_Home_Page" %}">
                                        <i class="fal fa-store"></i>
                                            صفحه اصلی فروشگاه
                                    </a>
                                </div>
                                <div class="item-menu">
                                    <a href="{% url "module_orders:urls_cart" %}">
                                        <i class="fal fa-shopping-bag"></i>
                                        سبد خرید
                                    </a>
                                </div>
                            </div>


                            <ul>
                                <li class="MyAccount-navigation-link MyAccount-navigation-link-dashboard
                                 {% if "dashboard" in request.path %} is-active {% endif %}" >
                                    <a href="{% url "module_profile:urls_profile_view" %}">
                                        <i class="fal fa-tachometer"></i>
                                        پیشخوان
                                    </a>
                                </li>

                                {% if request.user.useradditional.IsSeller %}
                                    <li class="MyAccount-navigation-link MyAccount-navigation-link-seller
                                    {% if 'seller' in request.path %}
                                        is-active
                                    {% endif %}
                                     ">
                                        <a href="{% url "module_profile:urls_profile_seller_main" %}">
                                            <i class="fal fa-bags-shopping"></i>
                                            <span class="text-success">
                                            محصولات من
                                            </span>
                                        </a>
                                    </li>
                                {% endif %}



                                <li class="MyAccount-navigation-link MyAccount-navigation-link-orders
                                {% if "profile/orders_history" in request.path %} is-active {% endif %}" >
                                    <a href="{% url "module_profile:urls_profile_orders_history" %}">
                                        <i class="fal fa-shopping-basket"></i>
                                        سفارش ها
                                    </a>
                                </li>

                                <li class="MyAccount-navigation-link MyAccount-navigation-link-wishlists
                                {% if "profile/wishlist" in request.path %} is-active {% endif %}" >
                                    <a href="{% url "module_profile:urls_profile_wishlist" %}">
                                        <i id="wish_fa_{{ product.id }}" class="fal fa-heart"></i>
                                        علاقه مندی ها
                                    </a>
                                </li>
                                <li class="MyAccount-navigation-link MyAccount-navigation-link-edit-address
                                {% if request.path ==  "/profile/address_edit/" %} is-active {% endif %}" >
                                    <a href="{% url "module_profile:urls_profile_address_edit" %}">
                                        <i class="fal fa-home"></i>
                                        آدرس‌ گیرنده سفارشات
                                    </a>
                                </li>
                                <li class="MyAccount-navigation-link MyAccount-navigation-link-edit-account
                                {% if "edit_profile" in request.path %} is-active {% endif %}" >
                                    <a href="{% url "module_profile:urls_profile_edit_profile" %}">
                                        <i class="fal fa-user"></i>
                                        ویرایش حساب کاربری (تغییر رمز عبور)
                                    </a>
                                </li>
                                <li class="MyAccount-navigation-link MyAccount-navigation-link-customer-logout">
                                    <a href="{% url "module_users:urls_Logout" %}">
                                        <i class="fal fa-sign-in"></i>
                                        خروج از حساب کاربری
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <div class="col-lg-9 col-xs-12">
                        <div class="woocommerce-MyAccount-content">
                            <header class="user-header">
                                <div class="account-head-icon">
                                    <ul>
                                        <li>
                                            <a href="{% url "module_users:urls_Logout" %}" class="logout">
                                                <i class="fal fa-power-off"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url "module_profile:urls_profile_edit_profile" %}" class="setting">
                                                <i class="fal fa-cog"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url "urls_Home_Page" %}" class="home">
                                                <i class="fal fa-house-flood"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </header>

                            {% block row %}{% endblock %}

                        </div>
                    </div>
                </div>
            </div>
        </main>



        <!-- footer -->
        <footer class="user-footer">
            <div class="container">
                <div class="footer-down">
                    <div class="gototop">
                        <i class="fal fa-angle-up"></i>
                    </div>
                    <div class="copy-right">کلیه حقوق مادی و معنوی برای وبسایت ترموس محفوظ می باشد.</div>
                </div>
            </div>
        </footer>
        <!-- footer -->
    </body>

    <!-- JS Global Compulsory -->
    <script src="{% static "" %}js/plugins/jquery-3.6.0.min.js"></script>
    <script src="{% static "" %}js/plugins/popper.min.js"></script>
    <script src="{% static "" %}bootstrap/js/bootstrap.min.js"></script>
    <!-- JS Implementing Plugins -->
    <script src="{% static "" %}js/plugins/jquery.nice-select.min.js"></script>
    <script src="{% static "" %}js/plugins/swiper-bundle.min.js"></script>
    <script src="{% static "" %}js/plugins/countdown.min.js"></script>
    <script src="{% static "" %}js/plugins/theia-sticky-sidebar.min.js"></script>
    <script src="{% static "" %}js/plugins/nouislider.min.js"></script>
    <script src="{% static "" %}js/plugins/wNumb.js"></script>
    <!-- JS Template -->
    <script src="{% static "" %}js/main.js"></script>

    {% block extrajs %}{% endblock %}
</html>